# .github/workflows/security-testing.yml
name: Security Testing Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  schedule:
    # Run security tests weekly on Sundays
    - cron: '0 2 * * 0'

jobs:
  security-audit:
    name: Security Audit & Testing
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Run security linting
        run: npm run security:lint

      - name: Run Jest security tests
        run: npm run test:security
        env:
          NODE_ENV: test

      - name: Generate security test coverage
        run: npm run test:security -- --coverage --coverageDirectory=coverage-security

      - name: Upload security test results
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: security-test-results
          path: |
            coverage-security/
            test-results/

      - name: Run npm audit
        run: npm audit --audit-level moderate --json > audit-results.json || true

      - name: Check for high/critical vulnerabilities
        run: |
          if grep -q '"severity":\s*"high\|critical"' audit-results.json; then
            echo "High or critical vulnerabilities found!"
            exit 1
          fi

  sast-scan:
    name: Static Application Security Testing
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run CodeQL Analysis
        uses: github/codeql-action/init@v2
        with:
          languages: javascript

      - name: Autobuild
        uses: github/codeql-action/autobuild@v2

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2
        with:
          category: "/language:javascript"

  dependency-scan:
    name: Dependency Vulnerability Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run OWASP Dependency Check
        uses: dependency-check/Dependency-Check_Action@main
        with:
          project: 'Quiz App'
          path: '.'
          format: 'ALL'
          args: >
            --enableRetired
            --enableExperimental
            --nvdValidForHours 24

      - name: Upload dependency check results
        uses: actions/upload-artifact@v3
        with:
          name: dependency-check-report
          path: reports/

  container-security:
    name: Container Security Scan
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t quiz-app:security-scan .

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'image'
          scan-ref: 'quiz-app:security-scan'
          format: 'sarif'
          output: 'trivy-results.sarif'
          severity: 'CRITICAL,HIGH'

      - name: Upload Trivy scan results
        uses: github/codeql-action/upload-sarif@v2
        if: always()
        with:
          sarif_file: 'trivy-results.sarif'

      - name: Run Dockle (Docker image linter)
        uses: goodwithtech/dockle-action@v1
        with:
          image: 'quiz-app:security-scan'
          format: 'sarif'
          output: 'dockle-results.sarif'

      - name: Upload Dockle results
        uses: github/codeql-action/upload-sarif@v2
        if: always()
        with:
          sarif_file: 'dockle-results.sarif'

  dast-scan:
    name: Dynamic Application Security Testing
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Start application
        run: |
          npm ci
          npm run build
          npm run start &
          sleep 10

      - name: Run OWASP ZAP baseline scan
        uses: zaproxy/action-baseline@v0.10.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          docker_name: 'owasp/zap2docker-stable'
          target: 'http://localhost:3000'
          rules_file_name: '.zap/rules.tsv'
          cmd_options: '-a'
          fail_action: true

      - name: Upload ZAP scan results
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: zap-scan-report
          path: |
            report_html/*
            report_json/*
            report_md/*
            report_xml/*

  secrets-detection:
    name: Secrets Detection
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run TruffleHog OSS
        uses: trufflesecurity/trufflehog@main
        with:
          path: ./
          base: main
          head: HEAD
          extra_args: --debug --only-verified

  compliance-check:
    name: Security Compliance Check
    runs-on: ubuntu-latest
    if: always()
    needs: [security-audit, sast-scan, dependency-scan, secrets-detection]

    steps:
      - name: Check security job statuses
        run: |
          if [ "${{ needs.security-audit.result }}" = "failure" ]; then
            echo "Security audit failed"
            exit 1
          fi

          if [ "${{ needs.sast-scan.result }}" = "failure" ]; then
            echo "SAST scan failed"
            exit 1
          fi

          if [ "${{ needs.dependency-scan.result }}" = "failure" ]; then
            echo "Dependency scan failed"
            exit 1
          fi

          if [ "${{ needs.secrets-detection.result }}" = "failure" ]; then
            echo "Secrets detection failed"
            exit 1
          fi

          echo "All security checks passed!"

      - name: Create security compliance badge
        run: |
          echo "✅ Security checks passed" > security-status.txt

      - name: Upload compliance status
        uses: actions/upload-artifact@v3
        with:
          name: security-compliance
          path: security-status.txt