[build]
  functions = "netlify/functions"
  publish   = "dist"

[[redirects]]
  path = "/api/auth/verifyPreAccess"
  to = "/.netlify/functions/auth/verifyPreAccess"
  status = 200

[[redirects]]
  path = "/api/auth/verifyUnlock"
  to = "/.netlify/functions/auth/verifyUnlock"
  status = 200

[[redirects]]
  path = "/api/admin/requestUnlock"
  to = "/.netlify/functions/admin/requestUnlock"
  status = 200

[[redirects]]
  path = "/api/admin/getDevUnlockKey"
  to = "/.netlify/functions/admin/getDevUnlockKey"
  status = 200

[[redirects]]
  path = "/api/generateUnlockKey"
  to = "/.netlify/functions/generateUnlockKey"
  status = 200

[[redirects]]
  path = "/api/discordInteractions"
  to = "/.netlify/functions/discordInteractions"
  status = 200

[[redirects]]
  path = "/api/assets"
  to = "/.netlify/functions/getAssets"
  status = 200

[[redirects]]
  path = "/api/commits"
  to = "/.netlify/functions/getCommits"
  status = 200

[[redirects]]
  path = "/*"
  to = "/index.html"
  status = 200